name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check Composer configuration
      run: composer validate --strict
    - name: Install dependencies
      run: composer install
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
    - name: Run unit tests
      run: phpunit
